Make cli auth case insensitive
dbt-msft/dbt-sqlserver pull request #113
Opened 2021-02-20 08:56 UTC by JCZuurmond

Fixes #100

2021-04-13 06:20 UTC, mikaelene commented
@swanderz I have not used the CLI. But does this looks good to you?

2021-04-13 15:12 UTC, swanderz requested changes
thanks @JCZuurmond! can you add a "under the hood"  bullet to `CHANGELOG.MD` under a `future` release heading?

2021-04-14 15:38 UTC, JCZuurmond commented
@swanderz : Is this ok?

2021-04-14 16:02 UTC, swanderz commented on CHANGELOG.md
> +- cli authentication is case insensitive. [#100](https://github.com/dbt-msft/dbt-sqlserver/issues/100)
```suggestion
- authentication now is case-insensitive and accepts both `CLI` and `cli` as options. [#100](https://github.com/dbt-msft/dbt-sqlserver/issues/100) thanks (@JCZuurmond)[https://github.com/JCZuurmond]
- add unit tests for azure-identity related token fetching
```

2021-04-14 16:02 UTC, swanderz approved these changes

2021-04-14 17:45 UTC, JCZuurmond commented
I think the tests are failing for a different reason.

2021-04-14 18:24 UTC, JCZuurmond commented
No worries! Take the time you need.

2021-06-23 05:43 UTC, merged