Automatically provision Azure AD users if enabled
dbt-msft/dbt-sqlserver pull request #286
Opened 2022-09-14 20:04 UTC by sdebruyn

This would automatically provision Azure AD users used in grants if they are not created in the database yet. This is using contained database users which would only be possible in Azure SQL and Azure Synapse.

2022-09-15 06:30 UTC, JCZuurmond commented
LGTM; Do you have a link to the docs of `sqlserver_get_grant_sql(relation, privilege, grantees)`? To know what the parameters are

2022-09-16 15:35 UTC, dataders requested changes
i love the auto user-creation feature. however, there looks to be too much happening inside of `sqlserver_get_grant_sql`. It's only supposed to create the GRANT statements 

perhaps the user creation logic would fit better into the [apply_grants](https://cs.github.com/dbt-labs/dbt-core/blob/f5a94fc77428426002ef2a908ebf57a32597a627/core/dbt/include/global_project/macros/adapters/apply_grants.sql#L139) macro? might make sense for this overridden version to be just on dbt-sqlserver first, then later we might be able to add a new conditional flow to the default__ version in dbt-core. i imagine this feature could be useful to others

2022-09-16 15:37 UTC, dataders commented
> LGTM; Do you have a link to the docs of `sqlserver_get_grant_sql(relation, privilege, grantees)`? To know what the parameters are

@JCZuurmond check out the [global_project's apply_grants.sql](https://github.com/dbt-labs/dbt-core/blob/f5a94fc77428426002ef2a908ebf57a32597a627/core/dbt/include/global_project/macros/adapters/apply_grants.sql#L139) as well as the grant section of the 1.2 upgrade guide (https://github.com/dbt-labs/dbt-core/discussions/5468)

2022-09-16 16:47 UTC, sdebruyn commented
> perhaps the user creation logic would fit better into the [apply_grants](https://cs.github.com/dbt-labs/dbt-core/blob/f5a94fc77428426002ef2a908ebf57a32597a627/core/dbt/include/global_project/macros/adapters/apply_grants.sql#L139) macro? might make sense for this overridden version to be just on dbt-sqlserver first, then later we might be able to add a new conditional flow to the default__ version in dbt-core. i imagine this feature could be useful to others

@dataders Thank you for your review! Agree with the above. I changed it so that it better follows the intentions of the other macros in that file.

2022-09-19 08:40 UTC, sdebruyn commented on dbt/include/sqlserver/macros/adapters/apply_grants.sql
> +        if not exists(select name from sys.database_principals where name = '{{ grantee }}')
This check currently fails since it does the comparison on the safe user

2022-09-19 08:47 UTC, sdebruyn commented on dbt/include/sqlserver/macros/adapters/apply_grants.sql
> +        if not exists(select name from sys.database_principals where name = '{{ grantee }}')
fixed

2022-09-19 12:04 UTC, merged